### ISSUE TITLE
The dictionary is unnecessarily big!

### ISSUE THREAD

**Issue by district10** [ppwwyyxx/vim-PinyinSearch#1]
3000 chinese characters will be okay, 6000 is sufficiently good, 10000+ is not necessary.

I looked at `.dict` file, and found many chars I don't even know it's pinyin...

This may help: [Character frequency list of informative texts in Modern Chinese 现代汉语信息类文本单字列表](http://lingua.mtsu.edu/chinese-computing/statistics/char/list.php?Which=IN).

**Comment by ppwwyyxx** [comment]
I agree. Will update the dict soon.

**Comment by ppwwyyxx** [comment]
Fix with 72711c354e2107efdf6eb33ce98dbdc448536c08.
