### ISSUE TITLE
nvim 新版本不再工作

### ISSUE THREAD

**Issue by cxwx** [ppwwyyxx/vim-PinyinSearch#10]
nvim-0.10 无法正常工作

**Comment by ppwwyyxx** [comment]
I found no problems with neovim0.10. However there is a bug with python3.12 that was fixed just now: https://github.com/ppwwyyxx/vim-PinyinSearch/commit/2c87f51d14659018de77ad99e10cf95e62038144

**Comment by cxwx** [comment]
fixed
