### ISSUE TITLE
Is there any support for python3?

### ISSUE THREAD

**Issue by browneyedape** [ppwwyyxx/vim-PinyinSearch#3]
Error detected while processing function PinyinNext[1]..<SNR>14_Pinyin:
line    2:
E319: Sorry, the command is not available in this version: python << EOF
line    3:
E492: Not an editor command: import vim,sys
line    4:
E492: Not an editor command: ENCODING = vim.eval("&fileencoding")
...

**Comment by ppwwyyxx** [comment]
Why is this a problem of python3?
