### ISSUE TITLE
May I create similar capability for Obsidian?

### ISSUE THREAD

**Issue by anselmwang** [ppwwyyxx/vim-PinyinSearch#9]
Hi, @ppwwyyxx 

Thanks for creating `vim-PinyinSearch`, I love it so much!

I have implemented the same capability for Obsidian note taking software. Here is the [commit](https://github.com/anselmwang/obsidian-vimrc-support/commit/e74e305091fc4d798a3fd4d46f4ee948580ca139)

The algorithm is same as `vim-PinyinSearch`. So I will add acknowledgement to `vim-PinyinSearch`. 
May I know if you are fine with my implementation and what the LICENSE of `vim-PinyinSearch` is? 

For my code, originally I'd like to use MIT license.

Thanks,
Yu

**Comment by ppwwyyxx** [comment]
Hi, feel free to use it in Obsidian. I just added MIT license to the project.

**Comment by anselmwang** [comment]
Thanks a lot!

**Comment by anselmwang** [comment]
Here is the [Obsidian plugin](https://github.com/anselmwang/obsidian-vim-multibyte-char-search) , thanks for your help!
